ALTER TABLE equipment ADD COLUMN IF NOT EXISTS image_path TEXT;
ALTER TABLE equipment ADD COLUMN IF NOT EXISTS image_original_name VARCHAR(180);
ALTER TABLE equipment ADD COLUMN IF NOT EXISTS image_mime VARCHAR(80);
ALTER TABLE equipment ADD COLUMN IF NOT EXISTS image_size INTEGER;
