ALTER TABLE equipment ALTER COLUMN equipment_type_id DROP NOT NULL;
ALTER TABLE equipment ALTER COLUMN brand_id DROP NOT NULL;
ALTER TABLE equipment ALTER COLUMN model_id DROP NOT NULL;
ALTER TABLE equipment ALTER COLUMN location_id DROP NOT NULL;
ALTER TABLE equipment ALTER COLUMN area_id DROP NOT NULL;

ALTER TABLE stock_items ALTER COLUMN location_id DROP NOT NULL;
ALTER TABLE stock_items ALTER COLUMN area_id DROP NOT NULL;
